#!/usr/bin/env python3

import argparse
import itertools
import json

import binary


parser = argparse.ArgumentParser()
parser.add_argument('path', type=str, help='path to executable file')
parser.add_argument('--hex', action='store_true', help='hexadecimal output')
args = parser.parse_args()

bytes = open(args.path, 'rb').read()

info = {}

mz_header = binary.read_block(bytes, 0, 0x1c)
assert mz_header[:2] == b'MZ'

text_offset = binary.read_word(mz_header, 8) * 0x10
info['minimum-allocation'] = binary.read_word(mz_header, 0x0a) * 0x10
info['maximum-allocation'] = binary.read_word(mz_header, 0x0c) * 0x10
info['load-size'] = binary.read_word(mz_header, 4) * 0x200 - text_offset
info['text-size'] = (binary.read_word(mz_header, 4) - bool(binary.read_word(mz_header, 2))) * 0x200 + binary.read_word(mz_header, 2) - text_offset
info['entry-point'] = binary.read_word(mz_header, 0x16)*0x10 + binary.read_word(mz_header, 0x14)
info['entry-point-segment'] = binary.read_word(mz_header, 0x16)
info['stack-pointer'] = binary.read_word(mz_header, 0x10) + binary.read_word(mz_header, 0x0e)*0x10
info['stack-pointer-segment'] = binary.read_word(mz_header, 0x0e)
info['relocations'] = {}
relocation_table_base = binary.read_word(mz_header, 0x18)
segments = set()
for r in range(binary.read_word(mz_header, 6)):
    offset = binary.read_word(bytes, relocation_table_base + r*4)
    segment = binary.read_word(bytes, relocation_table_base + r*4 + 2)
    if len(bytes) < segment*0x10+offset+text_offset+2:
        raise RuntimeError(f'Too big relocation {segment:04X}:{offset:04X}.')
    value = binary.read_word(bytes, segment*0x10+offset+text_offset)
    segments.add(value*0x10)
    info['relocations'][segment*0x10+offset] = value * 0x10

ranges = [(0, info['text-size'])]
for a in sorted(segments):
    for i, (s, e) in enumerate(ranges):
        if s < a < e:
            ranges[i] = (a, e)
            ranges.insert(i, (s, a))
            break

info['bits'] = 16
info['machine'] = 'IMAGE_FILE_MACHINE_I386'
info['characteristics'] = ['IMAGE_FILE_EXECUTABLE_IMAGE']
info['sections'] = {
    f'.text{s//0x10:04x}' if s else '.text': {
        'address': s,
        'address-end': e,
        'characteristics': [
            'IMAGE_SCN_CNT_CODE',
            'IMAGE_SCN_CNT_INITIALIZED_DATA',
            'IMAGE_SCN_MEM_EXECUTE',
            'IMAGE_SCN_MEM_READ',
            'IMAGE_SCN_MEM_WRITE'
        ],
        'raw-offset': text_offset + s,
        'raw-size': e-s,
    } for s, e in ranges
}
if info['minimum-allocation'] > 0:
    info['sections']['.bss'] = {
        'address': info['load-size'],
        'address-end': info['load-size'] + info['minimum-allocation'],
        'characteristics': [
            'IMAGE_SCN_CNT_UNINITIALIZED_DATA',
            'IMAGE_SCN_MEM_READ',
            'IMAGE_SCN_MEM_WRITE'
        ],
        'raw-offset': info['text-size'] + text_offset,
        'raw-size': 0,
    }
info['subsystem'] = 'IMAGE_SUBSYSTEM_NATIVE'
info['directories'] = {}
info['imports'] = []
info['exports'] = []
info['resources'] = []

# Export.

if args.hex:
    def hexify(x):
        if isinstance(x, list):
            for index, item in enumerate(x):
                if isinstance(item, int):
                    x[index] = hex(item)
                else:
                    hexify(item)

        elif isinstance(x, dict):
            for key, value in x.items():
                if isinstance(value, int):
                    x[key] = hex(value)
                else:
                    hexify(value)
            y = {hex(k) if isinstance(k, int) else k: v for k, v in x.items()}
            x.clear()
            x |= y

    hexify(info)

info = dict(sorted(info.items()))

print(json.dumps(info, indent=4))
